---
roles:
  private_network:
    provisioners:
      - type: hosts
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
  proxy_client: {}
#  proxy_client:
#    provisioners:
#      - type: shell
#        inline: |-
#          iptables -I OUTPUT 1 -p tcp --destination-port 443 -j REJECT
#          iptables -I OUTPUT 2 -p tcp --destination-port 80 -j REJECT
  proxy_server:
    provisioners:
      - type: shell
        inline: |-
          yum -y install puppet
          puppet module install puppetlabs-stdlib
          puppet module install thias-squid3
      - type: shell
        inline: |-
          puppet apply -e 'include squid3'
          puppet apply -e "service { 'iptables': ensure => stopped }"
