---
vms:
  - name: proxy-client
    box: 'puppetlabs/debian-7.8-64-puppet'
    roles: ['proxy_client', 'private_network']
    provisioners:
      - type: shell
        inline: |-
          gem install bundler
      - type: puppet
        manifest_path: 'manifests/nfs.pp'
  - name: proxy-server
    box: 'puppetlabs/debian-7.8-64-puppet'
    roles: ['proxy_server', 'private_network']

